name: Testes Automatizados

on:
  push:
    branches:
      - main

jobs:

  testes:

    runs-on: ubuntu-latest

    steps:

      - name: Clonar projeto
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Executar testes API
        run: |
          pytest api_tests/tests -v

      - name: Executar testes WEB
        run: |
          pytest web_tests/tests -v